### ISSUE TITLE
Changing the order of the buttons to be from left to right minimize, maximize, close

### ISSUE THREAD

**Issue by piotrowskiadam** [krve/hyper-mac-controls#10]
With the extension and `flipped: false`
I was able to achieve

![image](https://user-images.githubusercontent.com/55131509/171412537-2557312c-7932-4f13-a073-a48b3a1676ac.png)

However I don't know how to put these buttons in different order which I want:
minimize, maximize, close

**Comment by Ben-sys32** [comment]
![image](https://github.com/user-attachments/assets/e681e8d5-d88b-470f-8cba-6b9bb5b25eb0)
like that?

**Comment by piotrowskiadam** [comment]
yellow green red. Basically, reproducing this behavior

![obraz](https://github.com/user-attachments/assets/65a84baf-567b-4fc8-9cef-2976fcfcfbb1)

Btw. I'm no longer user of hyper so if it comes to me we can close the issue.
