### ISSUE TITLE
Mac controls not fitting on window?

### ISSUE THREAD

**Issue by manelet** [krve/hyper-mac-controls#5]
How can I fix this?

![screen shot 2018-03-29 at 15 42 50](https://user-images.githubusercontent.com/765890/38092219-ed33029e-3367-11e8-8e0c-0e38e0883a73.png)

Thanks!

**Comment by krve** [comment]
What OS are you using?

I'll take a look at it soon.

**Comment by manelet** [comment]
macOS Sierra Version: 10.12.6 (16G29)

Thanks! 👍

**Comment by krve** [comment]
I'm not sure if it is fixed in the latest release. Could you please try that?

If it still doesn't work, could you test other "window control" packages to see if you have the same issue?

**Comment by manelet** [comment]
Still the same. I guess I'm gonna have to update macosx sooner than later  😔

![screen shot 2018-04-23 at 08 33 37](https://user-images.githubusercontent.com/765890/39110333-091c303a-46d1-11e8-85ba-2fa8d066f9a3.png)

**Comment by aleesilva** [comment]
not working on ubuntu version **20.04**?

**Comment by krve** [comment]
Should be fixed in the latest version https://github.com/krve/hyper-mac-controls/releases/tag/v1.2.0
