### ISSUE TITLE
Flip?

### ISSUE THREAD

**Issue by jamessewell** [krve/hyper-mac-controls#6]
Will flip sides be coming back?

**Comment by krve** [comment]
Yes! I just haven't had the time to do it yet. I'll try to look at it this weekend :+1:

**Comment by krve** [comment]
I found time to do it now. I've now added it in the latest release
https://github.com/krve/hyper-mac-controls/releases/tag/1.1.2

**Comment by jamessewell** [comment]
Amazing turnaround! Thanks!
