### ISSUE TITLE
Icon does not work in Ubuntu 18.04

### ISSUE THREAD

**Issue by tokuma09** [krve/hyper-mac-controls#7]
In Ubuntu 18.04, we can change icons using this package. However, it does not work such as maximization window etc. 

Is this a default setting of this package? Are there some bugs in this package?

![Screenshot from 2019-03-10 12-05-57](https://user-images.githubusercontent.com/32564723/54080142-f932f880-432c-11e9-9e54-d6068a05ebee.png)

**Comment by krve** [comment]
I'm currently using the package on Ubuntu 18.04 and it seems to work fine.

What exactly is the issue? Do the buttons not work?

**Comment by tokuma09** [comment]
Yes, bottons don't work.  How can I fix it?

**Comment by krve** [comment]
What version of Hyper.js are you using? (`hyper version` in your terminal)
Are you using the latest version of this package? The command below should help.
`cat ~/.hyper_plugins/node_modules/hyper-mac-controls/package.json`

**Comment by tokuma09** [comment]
`hyper version` returns 2.1.2.
And `cat ~/.hyper_plugins/node_modules/hyper-mac-controls/package.json` returns
```{
  "name": "hyper-mac-controls",
  "version": "1.1.2",
  "description": "Hyper mac-like window controls on linux or windows",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/krve/hyper-mac-controls.git"
  },
  "keywords": [
    "hyper",
    "hyperterm",
    "hyper-plugin",
    "hyperterm-plugin",
    "plugin",
    "mac"
  ],
  "author": "Kristoffer <kristoffer@krve.io>",
  "license": "MIT"
}
```

**Comment by krve** [comment]
What packages are you using besides `hyper-mac-controls`?

**Comment by tokuma09** [comment]
My plugins are as follows. 
```
  plugins: [
    'hyper-flat',
    'hypercwd',
    'hyperterm-material',
    "hyper-search",
    "hyper-statusline",
    "hyper-tab-icons",
    "hyper-material-theme",
    "hyper-tabs-enhanced",
    "hyper-pane",
    "hyperborder",
    "hyper-mac-controls"
  ],
```

**Comment by krve** [comment]
It seems the `hyperborder` plugin is causing the issue. It changes the header, so that it overlaps the buttons which causes the issue.

**Comment by tokuma09** [comment]
Thanks a lot! It works!
