### ISSUE TITLE
plugin crash

### ISSUE THREAD

**Issue by Lvzhenqian** [krve/hyper-mac-controls#8]
hyper version: 3.1.5
os: deepin 20.3

error message: `TypeError: Cannot read properties of undefined (reading 'getCurrentWindow')`
![截图_选择区域_20220108112329](https://user-images.githubusercontent.com/17487028/148629992-7dac673c-005e-44ae-9eff-3df5c4f2e210.png)

error file: `/home/charles/.config/hyper/.hyper_plugins/node_modules/hyper-mac-controls/index.js`

**Comment by krve** [comment]
Thanks for the error report!

I've just pushed a new release that should fix your issue: https://github.com/krve/hyper-mac-controls/releases/tag/v1.2.0

If you have any more issues, get back to me and I'll take a look at it 👍
