### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by ekurt** [krve/hyper-mac-controls#9]
It stopped working on Ubuntu (20.04) with the last Hyper (3.1.5) update.

**Comment by krve** [comment]
> It stopped working on Ubuntu (20.04) with the last Hyper (3.1.5) update.

Which version of the plugin are you using?

**Comment by ekurt** [comment]
> Which version of the plugin are you using?

How can I check the version of the plugin?

**Comment by krve** [comment]
You can try updating the plugin by installing it again: `hyper i hyper-mac-controls` as a new version was just released yesterday.

If that doesn't work, i'll test it out on Ubuntu 20.04 with the latest Hyper update to ensure it works.

**Comment by ekurt** [comment]
I update plugins and problem solved. Thanks for helping.
